export const achievementDefs = [
  {
    id: 'survive-15min',
    no: 1,
    name: '死神を見た',
    description: '15分生存する',
    type: 'surviveTime',
    seconds: 15 * 60,
  },
  {
    id: 'unlock-dmgcut',
    no: 2,
    name: '被ダメ軽減解禁',
    description: '実績の「済」を3つ達成する',
    type: 'achievementCount',
    count: 3,
  },
  {
    id: 'unlock-ignition',
    no: 3,
    name: 'イグニッション解禁',
    description: '難易度「むずかしい」を3つ済にする',
    type: 'hardClearCount',
    count: 3,
  },
  {
    id: 'deal-1500',
    no: 4,
    name: 'デカダメージ',
    description: '一撃で1000以上ダメージを出す',
    type: 'maxDamage',
    damage: 1000,
  },
  {
    id: 'card-master',
    no: 5,
    name: 'カードマスター',
    description: 'カードを累計30回使用する',
    type: 'cardUsageCount',
    count: 30,
  },
  {
    id: 'defeat-rainbow-slime',
    no: 6,
    name: 'スペシャル撃破',
    description: '虹色のスライムを撃破する',
    type: 'specialKill',
  },
  {
    id: 'toxic-melon-pan',
    no: 7,
    name: '毒メロンパン',
    description: 'ステージ「メロンパン毒沼」で毒沼ダメージを500以上受け、難易度「ふつう」以上でクリアする',
    type: 'poisonDamageClear',
    stage: 'メロンパン毒沼',
    difficulty: 'ふつう',
    damage: 500,
  },
  {
    id: 'melon-pan-lover',
    no: 8,
    name: 'デブ',
    description: '1回の戦闘でメロンパンを5個以上食べてクリア（レインボーメロンパン/レシピカードカード「おいしいメロンパン」可）',
    type: 'melonPanClear',
    count: 5,
  },
  {
    id: 'hp-half-hard-clear',
    no: 9,
    name: '縛りプレイ',
    description: '体力半減を有効にした状態で難易度「ふつう」以上をクリア',
    type: 'hpHalfHardClear',
    difficulty: 'ふつう',
  },
  {
    id: 'shopaholic',
    no: 10,
    name: '買い物好き',
    description: 'ショップで5つ以上物を購入',
    type: 'shopPurchaseCount',
    count: 5,
  },
  {
    id: 'unlock-gallery',
    no: 11,
    name: 'ギャラリー解禁',
    description: '実績の「済」を5つ達成する',
    type: 'achievementCount',
    count: 5,
  },
  {
    id: 'clear-industrial-district',
    no: 12,
    name: '産業革命',
    description: 'ステージ「メロンパン工業地帯」をクリアする',
    type: 'stageClear',
    stage: 'メロンパン工業地帯',
  },
  {
    id: 'ignition-master',
    no: 13,
    name: 'イグニッションマスター',
    description: '「イグニッションモード」をオンでクリアする',
    type: 'ignitionClear',
    difficulty: 'むずかしい',
  },
];
