export const cardDefs = [
  {
    id: 'deliciousMelonPan',
    name: 'おいしいメロンパン',
    attr: 1,
    rarity: 1,
    price: 1000,
    effect: '使うと20回復する',
  },
  {
    id: 'chocoSauce',
    name: 'チョコソース',
    attr: 1,
    rarity: 1,
    price: 1200,
    effect: '使うとHPを5回復し、デッキに「おいしいメロンパン」があると合計回復量が3倍になる',
  },
  {
    id: 'speedMelonPan',
    name: '加速メロンパン',
    attr: 2,
    rarity: 1,
    price: 2500,
    effect: '使うと30秒移動速度が1.1倍早くなる',
  },
  {
    id: 'redMelonPan',
    name: '赤メロンパン',
    attr: 3,
    rarity: 1,
    price: 2500,
    effect: '使うと通常攻撃に火属性を付与する',
  },
  {
    id: 'hyperSpeedMelonPan',
    name: '超加速メロンパン',
    attr: 4,
    rarity: 2,
    price: 5500,
    effect: '使うと30秒移動速度が1.3倍早くなる',
  },
  {
    id: 'decoyMelonPan',
    name: 'デコイメロンパン',
    attr: 5,
    rarity: 2,
    price: 5500,
    effect: '使うとあんどーのデコイを1体召喚する',
  },
  {
    id: 'oniMelonPan',
    name: '鬼メロンパン',
    attr: 6,
    rarity: 2,
    price: 5500,
    effect: '使うと30秒全ての攻撃力が1.2倍になる',
  },
  {
    id: 'gekioniMelonPan',
    name: '劇鬼メロンパン',
    attr: 7,
    rarity: 3,
    price: 10500,
    effect: '使うと1分間攻撃力が1.5倍になる',
  },
  {
    id: 'knockbackMelonPan',
    name: 'ノックバックメロンパン',
    attr: 8,
    rarity: 4,
    price: 18500,
    effect: '使うと12秒自身に強力なノックバック（敵吹き飛ばし）を付与する',
  },
  {
    id: 'invincibleMelonPan',
    name: '無敵メロンパン',
    attr: 8,
    rarity: 4,
    price: 20500,
    effect: '使うと7秒無敵になる',
  },
  {
    id: 'blueMelonPan',
    name: '青メロンパン',
    attr: 9,
    rarity: 1,
    price: 2500,
    effect: '使うと通常攻撃に氷属性を付与する',
  },
  {
    id: 'yellowMelonPan',
    name: '黄メロンパン',
    attr: 10,
    rarity: 1,
    price: 2500,
    effect: '使うと通常攻撃に雷属性を付与する',
  },
  {
    id: 'blackMelonPan',
    name: '黒メロンパン',
    attr: 11,
    rarity: 1,
    price: 2500,
    effect: '使うと通常攻撃に闇属性を付与する',
  },
  {
    id: 'fatMelonPan',
    name: 'デブメロンパン',
    attr: 12,
    rarity: 2,
    price: 5500,
    effect: '使うと30秒移動速度が0.8倍になるが被ダメージが0.8倍になる',
  },
  {
    id: 'superDecoyMelonPan',
    name: '超デコイメロンパン',
    attr: 13,
    rarity: 3,
    price: 10500,
    effect: '使うとフィールドのランダムな場所にあんどーのデコイを10体召喚する',
  },
  {
    id: 'piercingShot',
    name: '貫通',
    attr: 16,
    rarity: 2,
    price: 5500,
    effect: '7秒間通常弾が貫通する',
  },
  {
    id: 'recipeResearch',
    name: 'レシピ研究',
    attr: 15,
    rarity: 2,
    price: 7500,
    effect: '以降戦闘終了まで金と虹のカードオーブ出現率が1.2倍になる',
  },
  {
    id: 'cardEater',
    name: 'カード食い',
    attr: 14,
    rarity: 1,
    price: 3850,
    effect: '以降戦闘終了までカード使用時HP10回復（使用後除外）',
  },
];

// デフォルトエクスポートも用意しておくことで、
// どのモジュール形式からでもカード定義を確実に読み込めるようにする
export default cardDefs;
